In [31]:
import numpy as np
# Life w/o numpy to life with numpy
import math

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:

In [ ]:
''' 
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list'''

In [9]:
sum_of_a = [sum(a)]
print('sum of a: ', sum_of_a)

sum of a:  [55]


In [ ]:
'''# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list '''

In [11]:
min_of_a = min(a)
print(min_of_a)

1


In [ ]:
'''# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list  '''

In [13]:
max_of_a = max(a)
print(max_of_a)

10


In [ ]:
''' # Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list'''

In [19]:
mean_of_a = np.mean(a)
print(mean_of_a)

5.5


In [ ]:
''' # Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together'''

In [23]:
product_of_a = np.prod(a)
print(product_of_a)

3628800


In [ ]:
''' # Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]'''

In [46]:
square_of_a = np.square(a)
print(square_of_a)

[  1   4   9  16  25  36  49  64  81 100]


In [ ]:
''' # Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers '''

In [57]:

odds_in_a = [n for n in a if n%2=1]
print(odds_in_a)

[1, 3, 5, 7, 9]


In [ ]:
''' # Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.'''

In [58]:
evens_in_a = [n for n in a if n%2!=1]
print (evens_in_a)

[2, 4, 6, 8, 10]


# ## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...

In [1]:
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [59]:
flattened_list=[]
for numbers in b:
    for n in numbers:
        flattened_list.append(n)
flattened_list

[3, 4, 5, 6, 7, 8]

In [2]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)



In [60]:
sum_b= sum(flattened_list)
sum_b

33

In [ ]:

# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

In [61]:
min_b = min(flattened_list)
min_b

3

In [ ]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

In [62]:
max_b = max(flattened_list)
max_b

8

In [ ]:

# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [63]:
mean_b= np.mean(flattened_list)
mean_b


5.5

In [ ]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

In [66]:
pro_b= np.prod(flattened_list)
pro_b

20160

In [ ]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

In [67]:
b = np.array(b)
b**2

array([[ 9, 16, 25],
       [36, 49, 64]])

In [ ]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

In [71]:
odds_in_b = [n for n in flattened_list if n%2 !=0]
odds_in_b

[3, 5, 7]

In [ ]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

In [74]:
evens_in_b = [n for n in flattened_list if n%2 ==0]
evens_in_b

[4, 6, 8]

In [ ]:
# Exercise 9 - print out the shape of the array b.

In [75]:
b.shape

(2, 3)

In [ ]:

# Exercise 10 - transpose the array b.

In [78]:
b.T

array([[3, 6],
       [4, 7],
       [5, 8]])

In [ ]:

# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [79]:
b.flatten()

array([3, 4, 5, 6, 7, 8])

In [ ]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [81]:
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [82]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
c=np.array(c)

In [ ]:
# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.



In [ ]:
''' # Exercise 1 - Find the min, max, sum, and product of c.'''

In [83]:
{
    'sum': c.sum(),
    'min': c.min(),
    'max': c.max(),
    'sum':c.sum(),
    'product': c.prod()
}

{'sum': 45, 'min': 1, 'max': 9, 'product': 362880}

In [ ]:
''' # Exercise 2 - Determine the standard deviation of c.'''

In [84]:
c.std()

2.581988897471611

In [ ]:
''' # Exercise 3 - Determine the variance of c.'''

In [85]:
c.var()

6.666666666666667

In [ ]:
''' # Exercise 4 - Print out the shape of the array c'''

In [86]:
c.shape

(3, 3)

In [ ]:
''' # Exercise 5 - Transpose c and print out transposed result.'''

In [87]:
c.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
''' # Exercise 6 - Get the dot product of the array c with c. '''

In [88]:
np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
''' # Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261'''

In [90]:
(c*c.T).sum()

261

In [ ]:
''' # Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.'''

In [91]:
(c*c.T).prod()

131681894400

In [92]:
## Setup 4

d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

d=np.array(d)

In [93]:
# Exercise 1 - Find the sine of all the numbers in d


np.sin(d)


array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [94]:
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d)


array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [95]:
# Exercise 3 - Find the tangent of all the numbers in d

np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [96]:

# Exercise 4 - Find all the negative numbers in d

d[d<0]

array([-90, -30, -45, -45])

In [98]:
# Exercise 5 - Find all the positive numbers in d

d[d>0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [99]:
# Exercise 6 - Return an array of only the unique numbers in d.

np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [100]:

# Exercise 7 - Determine how many unique numbers there are in d.

np.unique(d).size

11

In [101]:

# Exercise 8 - Print out the shape of d.
d.shape

(3, 6)

In [102]:

# Exercise 9 - Transpose and then print out the shape of d.

d.T.shape

(6, 3)

In [103]:

# Exercise 10 - Reshape d into an array of 9 x 2
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])