In [1]:
import numpy as np 

In [2]:
a= np.array([4,10,12,23,-2,1,0,0,0,-6,3,-7])

In [3]:
a

array([ 4, 10, 12, 23, -2,  1,  0,  0,  0, -6,  3, -7])

In [ ]:
'''1.  How many negative numbers are there?'''

In [7]:
a[a < 0]


array([-2, -6, -7])

In [ ]:
''' 2.  How many positive numbers are there? '''

In [11]:
b = a[a >0]
b
len(b)

6

In [ ]:
''' 3. How many even positive numbers are there?'''

In [20]:
c = a[(a > 0) & (a% 2== 0)]
c
len(c)

3

In [ ]:
''' 4.  If you were to add 3 to each data point, how many positive numbers would there be?'''

In [29]:
ad3 = a+3
ad3

ad3[ad3 > 0]


array([ 7, 13, 15, 26,  1,  4,  3,  3,  3,  6])

In [ ]:
''' 5.  If you squared each number, what would the new mean and standard deviation be?'''

In [31]:
square = a**2 
square 

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [35]:
sm = square.mean()
sm

74.0

In [36]:
sstd= square.std()
sstd 

144.0243035046516

In [ ]:
''' 6. A common statistical operation on a dataset is centering. 
This means to adjust the data such that the mean of the data is 0. 
This is done by subtracting the mean from each data point. 
Center the data set. See this link for more on centering.'''

In [43]:
centered = a- a.mean()
centered.mean()

-1.4802973661668753e-16

In [45]:
''' 
 7. Calculate the z-score for each data point. Recall that the z-score is given by:

Z = (x − μ) / σ

'''

z = (a- a.mean())/ a.std()
z

array([ 0.10418928,  0.85435209,  1.10440636,  2.47970486, -0.64597353,
       -0.27089213, -0.39591926, -0.39591926, -0.39591926, -1.14608208,
       -0.02083786, -1.27110921])